### ISSUE TITLE
Explain the website's purpose in the README

### ISSUE THREAD

**Issue by dgobalak** [dgobalak/DocSurfer#16]
We should add a section to the README explaining what the website does and the process in which it does it (Text extraction -> Key word extraction -> Web scraping -> Summarization). Maybe create a flowchart and include the different algorithms we have for each step of the process. For example, include frequency-based as well as cluster-based summarization.

**Comment by Wrytarian** [comment]
Would this work as a description of the website's purpose? If so, I'll copy it to the readme.

DocSurfer extracts the names of people, places and things from a file and displays a Wikipedia summary describing each name. 

DocServer uses the following process: 

1. Prompts you for a file (allowable file types= pdf, audio, video, image). (Does it handle all file formats MP3/MP4, png/jpg/gif?) 

2. Depending on the file type:
    - Extracts text from the pdf or image. 
    - Converts audio/video to text. 

3. Searches text for [proper nouns](https://www.merriam-webster.com/dictionary/proper%20noun]). 

4. Finds the Wikipedia article for each proper noun.

5. Displays a summary of the Wikipedia article.


We are working on the following enhancements. Stay tuned!

- Using machine learning, create a caption for images with no text, and use the caption as the text.
- Use other encyclopedias/websites in addition to Wikipedia.
- Use Term frequency-Inverse document frequency (TF-IDF) to construct a summary from sentences containing the most important words in the article.
- Translate the summary to a user's language of choice.

**Comment by dgobalak** [comment]
Looks good! Just a few notes:
1. The supported file formats (at the moment) include:
- .wav
- .mp3
- .mp4
- .pdf
- .png

2. I added the translation functionality today, so you can remove that point in the enhancements section. You could also update point # 5 to something like "Displays a summary for each Wikipedia article, translated to the user's language of choice."
3. Could you change "DocServer" to "DocSurfer"? I'm planning on changing the project's name at some point. Just haven't decided yet.

**Comment by dgobalak** [comment]
It'd probably make sense to add what you wrote to the "About the Project" section of the readme.
